sudo: required

language: c++
dist: bionic

addons:
  apt:
    packages:
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglew-dev

os:
  - linux
#  - windows

compiler:
  - gcc
#  - clang

env:
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-10
  - sudo apt-get -y install g++-10
  - gcc-10 -v
  - g++-10 -v

install:
- if [ "$CXX" = "g++" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        export CXX="g++-9" CC="gcc-9";
      else
        export CXX="g++-10" CC="gcc-10";
    fi;
  fi

before_script:
  - sudo rm /usr/bin/python
  - sudo cp /usr/bin/python3 /usr/bin/python

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
  - cmake --build .

git:
  submodules: true

branches:
  only:
    - master
