sudo: required

language: c++
dist: bionic

addons:
  apt:
    packages:
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglew-dev
      - cmake

os:
  - linux
#  - windows

compiler:
  - gcc
#  - clang

env:
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

jobs:
  include:
    #Compile for desktop app
    - name: "Desktop app"
      install:
      - if [ "$CXX" = "g++" ]; then
          if [ "$TRAVIS_OS_NAME" = "osx" ]; then
              export CXX="g++-9" CC="gcc-9";
            else
              export CXX="g++-10" CC="gcc-10";
          fi;
        fi
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get -y install gcc-10
        - sudo apt-get -y install g++-10
        - gcc-10 -v
        - g++-10 -v
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
        - cmake --build . --target AWebWoWViewerCpp
    #Compile for emscripten
    - name: "Emscripten version"
      install:
        - git clone https://github.com/emscripten-core/emsdk.git
        - cd emsdk
        - git pull
        - ./emsdk install latest
        - ./emsdk activate latest
        - source ./emsdk_env.sh
        - cd ..
#        # Download and install latest cmake
#        - |
#          if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
#            CMAKE_URL="http://www.cmake.org/files/v3.18/cmake-3.18.2-Linux-x86_64.tar.gz"
#            mkdir -p ${DEPS_DIR}/cmake
#            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
#            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#          fi
      script:
        - mkdir build
        - cd build
        - cmake ../emscripten_port -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
        - cmake --build . --target project


before_script:
  - sudo rm /usr/bin/python
  - sudo cp /usr/bin/python3 /usr/bin/python



git:
  submodules: true

branches:
  only:
    - master
